### ISSUE TITLE
Not able to import the module with ParcelJS

### ISSUE THREAD

**Issue by ciberado** [Desousak/canvas-draw-js#2]
Hi! 

Adding an `import svgKetch from 'svg-pen-sketch';` raises this error:

```
/node_modules/svg-pen-sketch/dist/svg-pen-sketch.js:1:29655: Unexpected token (1:29655)
```

Is it possible the version uploaded to npm repository has some bug on it? (btw, thanks for creating this project :))

The relevant `package.json` line is:

```
    "svg-pen-sketch": "^1.0.8",
```

**Comment by Desousak** [comment]
Hey! Sorry for the delay in fixing this - I replaced the use of Webpack with ParcelJS which should fix the issues you were having.
